-- Add all missing columns at once
ALTER TABLE public.profiling_form_submissions 
ADD COLUMN כלים_ניהול_לידים TEXT[],
ADD COLUMN לידים_פייסבוק_חודשי BIGINT,
ADD COLUMN לידים_וואטסאפ_חודשי BIGINT,
ADD COLUMN לידים_אתר_חודשי BIGINT,
ADD COLUMN לידים_טלפון_חודשי BIGINT,
ADD COLUMN לידים_הפניות_חודשי BIGINT,
ADD COLUMN לידים_אחר_חודשי BIGINT,
ADD COLUMN מערכת_רישום_לידים TEXT,
ADD COLUMN תגובה_ראשונית_ללידים TEXT,
ADD COLUMN קריטריונים_סינון_לידים TEXT,
ADD COLUMN סוגי_תוכן_מיוצרים TEXT[],
ADD COLUMN מספר_אנשי_קשר_במאגר BIGINT,
ADD COLUMN מיקום_מאגר_לקוחות TEXT,
ADD COLUMN פילוח_מאגר_לקוחות TEXT[],
ADD COLUMN תהליך_פנייה_מחודשת TEXT,
ADD COLUMN כלים_שמירת_קשר TEXT[],
ADD COLUMN פגישות_שבועיות BIGINT,
ADD COLUMN תזכורות_שבועיות BIGINT,
ADD COLUMN תהליך_תיאום_פגישות TEXT,
ADD COLUMN משימות_חוזרות TEXT[],
ADD COLUMN שעות_מנהלה_שבועיות BIGINT,
ADD COLUMN תהליך_הפקת_מסמכים TEXT,
ADD COLUMN תוכנות_נוכחיות TEXT[],
ADD COLUMN פירוט_תהליך_עבודה_מרכזי TEXT,
ADD COLUMN סטטוס_תקציב TEXT,
ADD COLUMN סכום_תקציב BIGINT,
ADD COLUMN מדד_הצלחה_כמותי TEXT,
ADD COLUMN תאריך_התחלה TIMESTAMP WITHOUT TIME ZONE;